### ISSUE TITLE
'DisplayPacket' object has no attribute 'page_str' on running t42html

### ISSUE THREAD

**Issue by grim-fandango** [ali1234/vhs-teletext#2]
Hi Alistair,

I'm getting this on the latest commit:

Traceback (most recent call last):
  File "D:\My Documents\vhs-teletext2\t42html.py", line 14, in <module>
    service = make_service(sciter(reader(open(sys.argv[1]))))
  File "D:\My Documents\vhs-teletext2\teletext\t42\pipeline.py", line 85, in make_service
    for s in paginate(packet_iter, pages=pages, yield_func=subpages):
  File "D:\My Documents\vhs-teletext2\teletext\t42\pipeline.py", line 52, in paginate
    if magbuffers[mag][0].page_str() in pages:
AttributeError: 'DisplayPacket' object has no attribute 'page_str'

**Comment by ali1234** [comment]
This doesn't look related to anything recent. Line 51 of pipeline.py is supposed to prevent anything other than HeaderPacket from being evaluated, but a DisplayPacket got through.

If that doesn't fix it please send me the t42 you are trying to process.

**Comment by grim-fandango** [comment]
That latest commit fixes it, thanks!
